import Logo from "./components/Logo";
import Navigations from "./components/Navigations";

export const metadata = {
  title: "the wild oasis ",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Logo />
          <Navigations />
        </header>
        <main>{children}</main>
        <footer>this is copy right by wild oasis</footer>
      </body>
    </html>
  );
}
