import Counter from "@/app/_components/Counter";

export const metadata = {
  title: "cabins ",
  description: "Generated by Next.js",
};
export default function page() {
  return (
    <div>
      <h1>this is a cabin page</h1>
    </div>
  );
}
